use std::fmt::Write as _;
use std::path::PathBuf;

use anyhow::Result;

use crate::findings;
use crate::state::RitualDirs;

/// Cap per section: the newest dispositions matter, ancient ones age out.
const MAX_PER_SECTION: usize = 50;

/// Review memory distilled from finding dispositions — deterministic, no LLM.
/// Dismissed findings become a "known noise, do not re-flag" list the
/// dual-review skill reads before reviewing; fixed ones mark where real bugs
/// actually lived. Regenerated wholesale from the findings dir, so the file
/// is never hand-edited and never drifts.
pub fn generate(dirs: &RitualDirs) -> Result<Option<String>> {
    let loaded = findings::load_all(&dirs.findings_dir())?;
    // Newest-first walk; dedup on (title, location) with a repeat count so a
    // noise class dismissed five times reads as one weighted line.
    let mut noise: Vec<(String, usize)> = Vec::new();
    let mut real: Vec<(String, usize)> = Vec::new();
    for lf in &loaded {
        for f in &lf.file.findings {
            let bucket = match f.action.as_str() {
                "dismissed" => &mut noise,
                "fixed" => &mut real,
                _ => continue,
            };
            let loc = f.location();
            let entry = if loc.is_empty() {
                f.title.clone()
            } else {
                format!("{} ({loc})", f.title)
            };
            match bucket.iter_mut().find(|(e, _)| *e == entry) {
                Some((_, n)) => *n += 1,
                None => bucket.push((entry, 1)),
            }
        }
    }
    if noise.is_empty() && real.is_empty() {
        return Ok(None);
    }

    let mut md = String::from(
        "# Lessons (generated)\n\n\
         <!-- generated by `ritual lessons` from finding dispositions — do not hand-edit -->\n",
    );
    if !noise.is_empty() {
        md.push_str("\n## Known noise — do not re-flag (unless evidence is materially new)\n\n");
        for (entry, n) in noise.iter().take(MAX_PER_SECTION) {
            let times = if *n > 1 {
                format!(" ×{n}")
            } else {
                String::new()
            };
            writeln!(md, "- {entry}{times}").ok();
        }
    }
    if !real.is_empty() {
        md.push_str("\n## Confirmed real-bug areas — look here first\n\n");
        for (entry, n) in real.iter().take(MAX_PER_SECTION) {
            let times = if *n > 1 {
                format!(" ×{n}")
            } else {
                String::new()
            };
            writeln!(md, "- {entry}{times}").ok();
        }
    }
    Ok(Some(md))
}

/// Regenerate `.ritual/lessons.md` from the findings dir. Fully generated:
/// when no disposition exists (yet, or anymore) a previously written file is
/// removed rather than left stale. Returns the path when the file exists
/// after the refresh. Called before every dual-review spawn — pure fs, cheap.
pub fn refresh(dirs: &RitualDirs) -> Result<Option<PathBuf>> {
    let path = dirs.lessons_file();
    match generate(dirs)? {
        Some(md) => {
            std::fs::create_dir_all(dirs.root())?;
            let tmp = path.with_extension("md.tmp");
            std::fs::write(&tmp, md)?;
            std::fs::rename(&tmp, &path)?;
            Ok(Some(path))
        }
        None => {
            let _ = std::fs::remove_file(&path);
            Ok(None)
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn seed(dir: &std::path::Path, name: &str, json: &str) {
        std::fs::create_dir_all(dir).unwrap();
        std::fs::write(dir.join(name), json).unwrap();
    }

    #[test]
    fn dispositions_bucket_dedup_and_count() {
        let tmp = tempfile::tempdir().unwrap();
        let dirs = RitualDirs::new(tmp.path());
        seed(
            &dirs.findings_dir(),
            "20260712T000000Z-dual-review.json",
            r#"{"stage":"dual-review","findings":[
                {"title":"unwrap noise","file":"src/a.rs","line":1,"action":"dismissed"},
                {"title":"unwrap noise","file":"src/a.rs","line":1,"action":"dismissed"},
                {"title":"real race","file":"src/b.rs","line":9,"action":"fixed"},
                {"title":"still open","file":"src/c.rs","line":2,"action":"pending"}
            ]}"#,
        );
        let md = generate(&dirs).unwrap().expect("has lessons");
        assert!(md.contains("## Known noise"));
        assert!(md.contains("- unwrap noise (src/a.rs:1) ×2"));
        assert!(md.contains("## Confirmed real-bug areas"));
        assert!(md.contains("- real race (src/b.rs:9)"));
        assert!(!md.contains("still open"), "pending is not a lesson");
    }

    #[test]
    fn refresh_writes_and_removes_stale() {
        let tmp = tempfile::tempdir().unwrap();
        let dirs = RitualDirs::new(tmp.path());

        // Nothing resolved -> no file (and no error).
        assert!(refresh(&dirs).unwrap().is_none());
        assert!(!dirs.lessons_file().exists());

        let path = dirs
            .findings_dir()
            .join("20260712T000000Z-dual-review.json");
        seed(
            &dirs.findings_dir(),
            "20260712T000000Z-dual-review.json",
            r#"{"stage":"dual-review","findings":[{"title":"n","action":"dismissed"}]}"#,
        );
        assert!(refresh(&dirs).unwrap().is_some());
        assert!(
            std::fs::read_to_string(dirs.lessons_file())
                .unwrap()
                .contains("- n")
        );

        // Findings gone (pruned/reverted) -> the generated file goes too.
        std::fs::remove_file(path).unwrap();
        assert!(refresh(&dirs).unwrap().is_none());
        assert!(!dirs.lessons_file().exists(), "stale lessons removed");
    }

    #[test]
    fn sections_cap_at_fifty() {
        let tmp = tempfile::tempdir().unwrap();
        let dirs = RitualDirs::new(tmp.path());
        let items: Vec<String> = (0..60)
            .map(|i| format!(r#"{{"title":"noise {i}","action":"dismissed"}}"#))
            .collect();
        seed(
            &dirs.findings_dir(),
            "20260712T000000Z-dual-review.json",
            &format!(
                r#"{{"stage":"dual-review","findings":[{}]}}"#,
                items.join(",")
            ),
        );
        let md = generate(&dirs).unwrap().unwrap();
        assert_eq!(md.matches("- noise").count(), MAX_PER_SECTION);
    }
}
